### ISSUE TITLE
Add the ability to add time blocks in the past.

### ISSUE THREAD

**Issue by adealmeida** [tadgh/TogglBot#7]
It would also be great if it could be either relative to today or a day in the past.

For example, if today is Thursday, March 16th

`track myFancyProject monday 9:00AM-5:00PM working on TPS reports!` -- sets a time block for Monday, March 13th.

`track myFancyProject -2days 9:00AM-5:00PM working on TPS reports!` -- sets a time block for Tuesday, March 14th.

**Comment by StephenMPapadatos** [comment]
#8 is a possible fix

**Comment by tadgh** [comment]
Closed by 8dfc1b32e6fd1f49ad016444ad730fc2cf7106a9
